query Jobs($id: ID!) {
  application(id: $id) {
    id
    created
    email
    externals {
      name
      url
    }
    job {
      position
      location
      # type
    }
    avatarUrl
    visaStatus
    # messageStatus
  }
}
