query Jobs($limit: Int, $after: String) {
  applications(limit: $limit, after: $after) {
    cursor
    hasMore
    items {
      id
      created
      email
      # externals {
      #   name
      #   url
      # }
      job {
        position
        location
        # type
      }
      avatarUrl
      # visaStatus
      # messageStatus
    }
  }
}
