query Jobs($limit: Int, $after: String) {
  applications(limit: $limit, after: $after) {
    cursor
    hasMore
    items {
      id
      created
      email
      job {
        position
        location
      }
      avatarUrl
    }
  }
}
