platform :ios, '8.0'

target 'UenoInternalApp' do

  pod 'react-native-navigation', :path => '../node_modules/react-native-navigation'

  # Code Push
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # react-native-google-signin
  pod 'Google/SignIn'

  # Pods for Mobile Center
  pod 'RNMobileCenterShared', '~> 0.6.0'
  pod 'MobileCenter', '~> 0.10.1'

  # You don't necessarily need all of these subspecs, but this would be a typical setup.
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'DevSupport',
    # Add any other subspecs you want to use in your project
  ]

  # Add any other dependencies here, including any 3rd party native libraries that you depend on for
  # React Native.

end
